### ISSUE TITLE
Валидация поля "пароль"

### ISSUE THREAD

**Issue by MorozovP** [international-team-management/team-platform#128]
- Обязательное поле
- При вводе первого появляется кнопка "Глаз".
- от 8 до 22 символов.
- Латиница
- Цифры
- Пробел
- ! # $ % & ; + - . ,= ? ^^ _  { }  ~ 
 (запрещены "< > ( ) [ ] @ ' : \ /  *)

**Comment by Duzer61** [comment]
Если я правильно понял описание ТЗ, то нет условия обязательного присутствия тех или иных символов. Т.е. пароль может состоять например только из букв или только из цифр. Делаю пока в таком виде.

**Comment by MorozovP** [comment]
Это из требований тестеров. Видимо из соображений безопасности. Давай пока так как ты написал, но нужно быть готовым получить в последствии от них на эту тему баг репорт.

**Comment by BardDaniel** [comment]
> Это из требований тестеров. Видимо из соображений безопасности. Давай пока так как ты написал, но нужно быть готовым получить в последствии от них на эту тему баг репорт.

Да, такого условия нет. Наши требования в целом по валидным символам. Они не обязательно все должны присутствовать в пароле.
