### ISSUE TITLE
Внести исправления в модели Task и Project

### ISSUE THREAD

**Issue by MorozovP** [international-team-management/team-platform#169]
Исправить отношение моделей на ManyToOne

Задача может существовать только в рамках одного проекта. 

Возникшие вопросы:
- Для чего дублируется создание объекта TaskUser в модели Task (метод save) и в сериализаторе TaskPostSerializer (метод create)?
-

**Comment by Duzer61** [comment]
Необходимо дальше дорабатывать сериализаторы и вьюхи по Project и Task
